# Generated by Django 5.2.14 on 2026-05-14 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancha',
            name='es_salon',
            field=models.BooleanField(default=False),
        ),
    ]
