# Generated by Django 5.2.14 on 2026-05-18 22:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0002_cancha_es_salon'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='cancha_padel_extra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservas_padel_extra', to='reservas.cancha'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='fichas_bateo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reserva',
            name='incluye_padel',
            field=models.BooleanField(default=False),
        ),
    ]
