# Generated by Django 5.2.14 on 2026-05-21 15:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0004_reserva_usuario_alter_cancha_nombre_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cancha',
            name='es_salon',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='cancha_padel_extra',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='fichas_bateo',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='incluye_padel',
        ),
        migrations.AlterField(
            model_name='reserva',
            name='estado',
            field=models.CharField(default='CONFIRMADA', max_length=20),
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(max_length=20)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
