"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.2.14.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
from datetime import timedelta
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# ==============================================================================
# CONFIGURACIÓN DE SEGURIDAD (PRODUCCIÓN)
# ==============================================================================

# Leer la Secret Key desde las variables de entorno de Render, con un fallback local
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', 'django-insecure-5l%(oaymgl#@jm^*3%6-+%$zl6*eoj&8p4wpsm^^z&faxkck67')

# Desactivar DEBUG en producción (True solo si existe la variable localmente)
DEBUG = os.environ.get('DJANGO_DEBUG', 'True') == 'True'

# Permitir el dominio que te asigne Render y localhost para pruebas
ALLOWED_HOSTS = [
    'localhost',
    '127.0.0.1',
    '.onrender.com',  # Permite cualquier subdominio en Render automáticamente
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders',
    'reservas',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware', # Para servir archivos estáticos en Render
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# ==============================================================================
# BASE DE DATOS: CONFIGURACIÓN PARA AIVEN (MYSQL)
# ==============================================================================
# Usa variables de entorno para la URL de la base de datos (Ej: mysql://user:pass@host:port/db)
# Si no encuentra la variable, usará la base de datos local
DATABASES = {
    'default': dj_database_url.config(
        default='mysql://root:rootpassword@db:3306/padel_db',
        conn_max_age=600,
    )
}

# CONFIGURACIÓN SSL OBLIGATORIA PARA AIVEN (Solo aplica en producción)
if not DEBUG:
    DATABASES['default']['OPTIONS'] = {
        'ssl': {
            'ssl_mode': 'REQUIRED'
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# ==============================================================================
# CONFIGURACIÓN DE TOKENS (SIMPLE JWT EXTENDIDO)
# ==============================================================================

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ],
}

SIMPLE_JWT = {
    # El token de acceso ahora durará 15 días en lugar de 5 minutos
    'ACCESS_TOKEN_LIFETIME': timedelta(days=15),
    
    # El token de refresco durará 90 días en lugar de 24 horas
    'REFRESH_TOKEN_LIFETIME': timedelta(days=90),
    
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': False,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'AUTH_HEADER_TYPES': ('Bearer',),
}


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'es-mx'

# Ajustado para tu huso horario
TIME_ZONE = 'America/Hermosillo'

USE_I18N = True

USE_TZ = True


# ==============================================================================
# ARCHIVOS ESTÁTICOS (REQUERIDO PARA EL PANEL DE DJANGO EN RENDER)
# ==============================================================================

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Almacenamiento optimizado con WhiteNoise para entornos como Render o Heroku
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# ==============================================================================
# CONFIGURACIÓN DE CORS (CONEXIÓN DESDE VERCEL)
# ==============================================================================
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
    "http://127.0.0.1:5173",
    "https://garden-sport.vercel.app/", 
]

CORS_ALLOW_CREDENTIALS = True
